topic:
  name: first-avro-topic

server:
  port: 8082

spring:
  kafka:

    producer:
      bootstrap-servers: "127.0.0.1:9092"
      key-serializer: "org.apache.kafka.common.serialization.StringSerializer"
      value-serializer: "io.confluent.kafka.serializers.KafkaAvroSerializer"
      properties:
        schema:
          registry:
            url: "http://0.0.0.0:8083"
    consumer:
      bootstrap-servers: "127.0.0.1:9092"
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      auto-offset-reset: "earliest"
      properties:
        schema:
          registry:
            url: "http://0.0.0.0:8083"
        specific:
          avro:
            reader: "true"
      group-id: "my-kafka-avro-group"


